Publish app to GH Pages (#36)
* Publish app to GH Pages

* Install deps with npm run install:dependencies

* Pull git submodules

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,6 +15,7 @@ env:
   node_version: 14.x
   # github.event.repository.clone_url not available for on: schedule
   clone_url: https://github.com/Sage-Bionetworks/rocc-app.git
+  gh_pages_url: https://sage-bionetworks.github.io/rocc-app
   # github.event.repository.default_branch not available for on: schedule
   default_branch: main
 
@@ -38,87 +39,106 @@ jobs:
     # - name: Run e2e tests
     #   run: npm run e2e
 
-  # build-and-publish-storybook:
-  #   needs: [test]
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #   - uses: actions/checkout@v2
-  #   - name: Prepare
-  #     id: prep
-  #     run: |
-  #       VERSION=noop
-  #       PUSH=false
-  #       if [ "${{ github.event_name }}" = "schedule" ]; then
-  #         VERSION=nightly
-  #         PUSH=true
-  #       elif [[ $GITHUB_REF == refs/tags/* ]]; then
-  #         VERSION=${GITHUB_REF#refs/tags/}
-  #       elif [[ $GITHUB_REF == refs/heads/* ]]; then
-  #         VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
-  #         if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
-  #           VERSION=edge
-  #           PUSH=true
-  #         elif [ "develop" = "$VERSION" ]; then
-  #           # If the branch develop is the default branch, the doc will be pushed
-  #           # to the folder edge but not the folder develop..
-  #           PUSH=true
-  #         fi
-  #       elif [[ $GITHUB_REF == refs/pull/* ]]; then
-  #         VERSION=pr-${{ github.event.number }}
-  #         PUSH=false
-  #       fi
-  #       if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
-  #         MINOR=${VERSION%.*}
-  #         MAJOR=${MINOR%.*}
-  #         PUSH=true
-  #       fi
-  #       echo ::set-output name=version::${VERSION}
-  #       echo ::set-output name=version_major::${MAJOR}
-  #       echo ::set-output name=version_minor::${MINOR}
-  #       echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
-  #       echo ::set-output name=push::${PUSH}
-  #   - name: Use Node.js ${{ env.node_version }}
-  #     uses: actions/setup-node@v2.1.5
-  #     with:
-  #       node-version: ${{ env.node_version }}
-  #   - run: npm ci
-  #   - name: Build storybook
-  #     run: npm run build:storybook
-  #   - name: Commit storybook
-  #     run: |
-  #       git clone ${{ env.clone_url }} \
-  #         --branch gh-pages --single-branch gh-pages
-  #       # Update gh-pages: version specified
-  #       TARGET_DIR=gh-pages/${{ steps.prep.outputs.version }}/storybook
-  #       mkdir -p ${TARGET_DIR}
-  #       cp -R storybook-static/* ${TARGET_DIR}
-  #       # Update gh-pages: latest, major, and minor versions
-  #       if [ ! -z "${{ steps.prep.outputs.version_major }}" ]; then
-  #         # Update major version (e.g. "1.2.3" => "1")
-  #         TARGET_DIR=gh-pages/latest
-  #         mkdir -p ${TARGET_DIR}
-  #         cp -R storybook-static/${{ steps.prep.outputs.branch }}/* ${TARGET_DIR}
-  #         # Update major version (e.g. "1.2.3" => "1")
-  #         TARGET_DIR=gh-pages/${{ steps.prep.outputs.version_major }}
-  #         mkdir -p ${TARGET_DIR}
-  #         cp -R storybook-static/${{ steps.prep.outputs.branch }}/* ${TARGET_DIR}
-  #         # Update minor version (e.g. "1.2.3" => "1.2")
-  #         TARGET_DIR=gh-pages/${{ steps.prep.outputs.version_minor }}
-  #         mkdir -p ${TARGET_DIR}
-  #         cp -R storybook-static/${{ steps.prep.outputs.branch }}/* ${TARGET_DIR}
-  #       fi
-  #       cd gh-pages
-  #       git config --local user.email "action@github.com"
-  #       git config --local user.name "GitHub Action"
-  #       git add .
-  #       git commit -m "Update storybook" -a || true
-  #       # The above command will fail if no changes were present, so we ignore
-  #       # that.
-  #   - name: Push changes
-  #     if: steps.prep.outputs.push == 'true'
-  #     uses: ad-m/github-push-action@master
-  #     with:
-  #       branch: gh-pages
-  #       directory: gh-pages
-  #       github_token: ${{ secrets.GITHUB_TOKEN }}
-  #       force: true
+  build-and-publish:
+    needs: [test]
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2
+      with:
+        submodules: true
+    - name: Prepare
+      id: prep
+      run: |
+        VERSION=noop
+        PUSH=false
+        if [ "${{ github.event_name }}" = "schedule" ]; then
+          VERSION=nightly
+          PUSH=true
+        elif [[ $GITHUB_REF == refs/tags/* ]]; then
+          VERSION=${GITHUB_REF#refs/tags/}
+        elif [[ $GITHUB_REF == refs/heads/* ]]; then
+          VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
+          if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
+            VERSION=edge
+            PUSH=true
+          elif [ "develop" = "$VERSION" ]; then
+            # If the branch develop is the default branch, the doc will be pushed
+            # to the folder edge but not the folder develop..
+            PUSH=true
+          fi
+        elif [[ $GITHUB_REF == refs/pull/* ]]; then
+          VERSION=pr-${{ github.event.number }}
+          PUSH=false
+        fi
+        if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
+          MINOR=${VERSION%.*}
+          MAJOR=${MINOR%.*}
+          PUSH=true
+        fi
+        echo ::set-output name=version::${VERSION}
+        echo ::set-output name=version_major::${MAJOR}
+        echo ::set-output name=version_minor::${MINOR}
+        echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
+        echo ::set-output name=push::${PUSH}
+    - name: Use Node.js ${{ env.node_version }}
+      uses: actions/setup-node@v2.1.5
+      with:
+        node-version: ${{ env.node_version }}
+    - name: Install dependencies
+      run: |
+        npm run install:dependencies
+        npm install -g @angular/cli
+    - name: Build ROCC app
+      run: ng build --prod --baseHref="${{ env.gh_pages_url }}/${{ steps.prep.outputs.version }}/demo/"
+    # - name: Build storybook
+    #   run: npm run build:storybook
+    - name: Commit to gh-pages
+      run: |
+        git clone ${{ env.clone_url }} \
+          --branch gh-pages --single-branch gh-pages
+        # Update gh-pages: version specified
+        # STORYBOOK_TARGET_DIR=gh-pages/${{ steps.prep.outputs.version }}/storybook
+        # mkdir -p ${STORYBOOK_TARGET_DIR}
+        # cp -R storybook-static/* ${STORYBOOK_TARGET_DIR}
+        APP_TARGET_DIR=gh-pages/${{ steps.prep.outputs.version }}/app
+        mkdir -p ${APP_TARGET_DIR}
+        cp -R dist/* ${APP_TARGET_DIR}
+        # Update gh-pages: latest, major, and minor versions
+        if [ ! -z "${{ steps.prep.outputs.version_major }}" ]; then
+          # Update major version (e.g. "1.2.3" => "1")
+          # STORYBOOK_TARGET_DIR=gh-pages/latest/storybook
+          # mkdir -p ${STORYBOOK_TARGET_DIR}
+          # cp -R storybook-static/* ${STORYBOOK_TARGET_DIR}
+          APP_TARGET_DIR=gh-pages/latest/app
+          mkdir -p ${APP_TARGET_DIR}
+          cp -R dist/* ${APP_TARGET_DIR}
+          # Update major version (e.g. "1.2.3" => "1")
+          # STORYBOOK_TARGET_DIR=gh-pages/${{ steps.prep.outputs.version_major }}/storybook
+          # mkdir -p ${STORYBOOK_TARGET_DIR}
+          # cp -R storybook-static/* ${STORYBOOK_TARGET_DIR}
+          APP_TARGET_DIR=gh-pages/${{ steps.prep.outputs.version_major }}/app
+          mkdir -p ${APP_TARGET_DIR}
+          cp -R dist/* ${APP_TARGET_DIR}
+          # Update minor version (e.g. "1.2.3" => "1.2")
+          # STORYBOOK_TARGET_DIR=gh-pages/${{ steps.prep.outputs.version_minor }}/storybook
+          # mkdir -p ${STORYBOOK_TARGET_DIR}
+          # cp -R storybook-static/* ${STORYBOOK_TARGET_DIR}
+          APP_TARGET_DIR=gh-pages/${{ steps.prep.outputs.version_minor }}/app
+          mkdir -p ${APP_TARGET_DIR}
+          cp -R dist/* ${APP_TARGET_DIR}
+        fi
+        cd gh-pages
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update gh-pages" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # that.
+    - name: Push changes to gh-pages
+      if: steps.prep.outputs.push == 'true'
+      uses: ad-m/github-push-action@master
+      with:
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+        force: true
